spring:
  datasource:
    url: jdbc:mysql://${FREELANCE_DB_HOST:localhost}:3306/${FREELANCE_DB:freelance}
    username: ${FREELANCE_DB_USERNAME:sa}
    password: ${FREELANCE_DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update # careful in production!!!
  jackson:
    default-property-inclusion: NON_EMPTY
  mail:
    host: ${FREELANCE_SMTP_HOST}
    port: ${FREELANCE_SMTP_PORT}
    username: ${FREELANCE_SMTP_USERNAME}
    password: ${FREELANCE_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
springdoc:
  swagger-ui:
    path: swagger-ui