spring:
  datasource:
    url: jdbc:h2:mem:freelance
    driverClassName: org.h2.Driver
    username: ${FREELANCE_DB_USERNAME:sa}
    password: ${FREELANCE_DB_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true